name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'services/auth/**'

# TODO: define name of cluster for "name_of_digital_ocean_cluster"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/auth && docker build -t hanoirocker/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push hanoirocker/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save <name_of_digital_ocean_cluster>
      - run: kubectl rollout restart deployment auth-depl
